using System;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media;
using Windows.Foundation;

namespace KubeNavigator.Views.Controls;

/// <summary>
/// A vertical stacking panel that synchronizes the first column width
/// across all child Grids with at least two column definitions.
/// Use as the ItemsPanel for an ItemsControl to align title/value pairs.
/// </summary>
public partial class DetailsPanel : Panel
{
    protected override Size MeasureOverride(Size availableSize)
    {
        // Reset previously applied MinWidth so we measure natural sizes
        foreach (var child in Children)
        {
            if (FindChildGrid(child) is { ColumnDefinitions.Count: >= 2 } grid)
            {
                grid.ColumnDefinitions[0].MinWidth = 0;
            }
        }

        // First pass: measure all children with natural column sizing
        foreach (var child in Children)
        {
            child.Measure(availableSize);
        }

        // Find the widest first-column element across all rows
        double maxTitleWidth = 0;
        foreach (var child in Children)
        {
            if (
                FindChildGrid(child) is { ColumnDefinitions.Count: >= 2, Children.Count: > 0 } grid
                && grid.Children[0] is FrameworkElement title
            )
            {
                maxTitleWidth = Math.Max(maxTitleWidth, title.DesiredSize.Width);
            }
        }

        // Synchronize: set MinWidth on each first column and re-measure
        if (maxTitleWidth > 0)
        {
            var changed = false;
            foreach (var child in Children)
            {
                if (
                    FindChildGrid(child) is { ColumnDefinitions.Count: >= 2 } grid
                    && grid.ColumnDefinitions[0].MinWidth != maxTitleWidth
                )
                {
                    grid.ColumnDefinitions[0].MinWidth = maxTitleWidth;
                    changed = true;
                }
            }

            if (changed)
            {
                foreach (var child in Children)
                {
                    child.Measure(availableSize);
                }
            }
        }

        // Sum up desired sizes
        double totalHeight = 0;
        double maxWidth = 0;
        foreach (var child in Children)
        {
            totalHeight += child.DesiredSize.Height;
            maxWidth = Math.Max(maxWidth, child.DesiredSize.Width);
        }

        return new Size(
            double.IsInfinity(availableSize.Width) ? maxWidth : availableSize.Width,
            totalHeight
        );
    }

    protected override Size ArrangeOverride(Size finalSize)
    {
        double y = 0;
        foreach (var child in Children)
        {
            child.Arrange(new Rect(0, y, finalSize.Width, child.DesiredSize.Height));
            y += child.DesiredSize.Height;
        }

        return new Size(finalSize.Width, y);
    }

    /// <summary>
    /// Finds the Grid that is the direct visual child of the given element
    /// (typically a ContentPresenter generated by ItemsControl).
    /// </summary>
    private static Grid? FindChildGrid(UIElement element)
    {
        if (element is Grid grid)
            return grid;

        var count = VisualTreeHelper.GetChildrenCount(element);
        for (var i = 0; i < count; i++)
        {
            if (VisualTreeHelper.GetChild(element, i) is Grid childGrid)
                return childGrid;
        }

        return null;
    }
}
